# Generated by Django 4.0.4 on 2022-04-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainlib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_img_url',
            field=models.CharField(default='mainlib/<django.db.models.fields.UUIDField>.jpg', max_length=200),
        ),
    ]
