# Generated by Django 4.0.4 on 2022-04-29 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainlib', '0004_alter_books_book_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev', models.CharField(max_length=1000)),
                ('date_posted', models.DateTimeField()),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainlib.books')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
