# Generated by Django 4.0.4 on 2022-04-29 21:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainlib', '0006_bookreview_delete_bookreviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='BReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev', models.CharField(max_length=1000)),
                ('date_posted', models.DateTimeField()),
                ('book', models.ManyToManyField(to='mainlib.books')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_uuid', models.UUIDField(editable=False, unique=True)),
                ('last_viewed', models.DateTimeField()),
                ('archived', models.BooleanField(default=False)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userbooks',
            name='user',
        ),
        migrations.DeleteModel(
            name='BookReview',
        ),
        migrations.DeleteModel(
            name='UserBooks',
        ),
    ]
