# Generated by Django 4.0.4 on 2022-04-29 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainlib', '0007_breview_userbook_remove_userbooks_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev', models.CharField(max_length=1000)),
                ('date_posted', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainlib.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_uuid', models.UUIDField(editable=False, unique=True)),
                ('last_viewed', models.DateTimeField()),
                ('archived', models.BooleanField(default=False)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userbook',
            name='user',
        ),
        migrations.DeleteModel(
            name='BReview',
        ),
        migrations.DeleteModel(
            name='UserBook',
        ),
    ]
