# Generated by Django 4.0.4 on 2022-04-30 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainlib', '0010_bookreview_userbook_remove_uba_book_remove_uba_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainlib.books', unique=True),
        ),
    ]
