# Generated by Django 4.0.4 on 2022-05-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainlib', '0013_books_book_image_alter_books_book_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_image',
            field=models.ImageField(upload_to='C:\\Coding\\Python\\Django\\libsproject\\media/'),
        ),
    ]
